### ISSUE TITLE
Pasta só de fontes

### ISSUE THREAD

**Issue by LuccaPrado** [SnappyDroid/SnappyDroid_V1#4]
Para o projeto seria muito interessante deixar uma pasta só de fontes, por exemplo:

![screenshot from 2016-01-28 21-03-16](https://cloud.githubusercontent.com/assets/8813731/12658732/b9d0efd0-c602-11e5-80f2-b7cc9a80dc4f.png)

Facilitaria muito na Organização do código :3

**Comment by sinesiobittencourt** [comment]
Opa! Show mesmo, vou dar uma olhada.

Obrigado.
